index:
    path: /
    controller: App\Controller\DefaultController::index

# Products
products_list:
    path: /products/{id}/{page}
    controller: App\Controller\ProductController::listProducts
    defaults: { page: 1 }
    requirements:
        id: \d+
        page: \d+

product_view:
    path: /product/{id}
    controller: App\Controller\ProductController::viewProduct
    requirements:
        id: \d+

product_quick_view:
    path: /product/quick/{id}
    controller: App\Controller\ProductController::quickviewProduct
    requirements:
        id: \d+

# Orders / Cart
cart_view:
    path: /cart
    controller: App\Controller\CartController::viewCart
    requirements:
        id: \d+

add_to_cart:
    path: /add_to_cart/{id}
    controller: App\Controller\CartController::addToCart
    methods: [GET,POST]
    options:
        expose: true
    requirements:
        id: \d+

load_top_cart:
    path: /top-cart
    controller: App\Controller\CartController::loadTopCart
    methods: [GET,POST]
    options:
        expose: true

# Wishlist
add_to_wishlist:
    path: /wishlist/{id}
    controller: App\Controller\WishlistController::addToWishlist
    methods: [GET,POST]
    options:
        expose: true
    requirements:
        id: \d+

# Blog


# User Account
user_account:
    path: /user-account
    controller: App\Controller\UserAccountController::index

user_registration:
    path: /user-registration
    controller: App\Controller\UserAccountController::register