index:
    path: /
    controller: App\Controller\DefaultController::index

404:
    path: /404-not-found
    controller: App\Controller\DefaultController::notFound

# Cron Jobs
create_categories:
    path: /create-categories
    controller: App\Controller\CreateCategoriesController::createCategories

# Products
products_list:
    path: /products/{id}/{page}
    controller: App\Controller\ProductController::listProducts
    defaults: { page: 1 }
    requirements:
        id: \d+
        page: \d+

product_view:
    path: /product/{id}
    controller: App\Controller\ProductController::viewProduct
    requirements:
        id: \d+

product_quick_view:
    path: /product/quick/{id}
    controller: App\Controller\ProductController::quickviewProduct
    requirements:
        id: \d+

product_search:
    path: /product/search
    controller: App\Controller\ProductController::searchResults
    methods: [POST]

# Orders / Cart
cart_view:
    path: /cart
    controller: App\Controller\CartController::viewCart

update_cart:
    path: /update-cart
    controller: App\Controller\CartController::updateCart
    methods: [POST]

add_to_cart:
    path: /add_to_cart
    controller: App\Controller\AjaxCartController::addToCart
    methods: [POST]
    options:
        expose: true

load_top_cart:
    path: /top-cart
    controller: App\Controller\AjaxCartController::loadTopCart
    methods: [GET,POST]
    options:
        expose: true

delete_top_cart_item:
    path: /delete-top-cart-item/
    controller: App\Controller\AjaxCartController::deleteTopCartItem
    methods: [GET,POST]
    options:
        expose: true

delete_cart_item:
    path: /delete-cart-item/{id}
    controller: App\Controller\CartController::deleteCartItem
    requirements:
        id: \d+

# Orders Checkout
checkout:
    path: /checkout/{step}
    controller: App\Controller\CheckoutController::checkout
    defaults: { step: 1 }
    requirements:
        id: \d+

# Wishlist
wishlist_view:
    path: /wishlist
    controller: App\Controller\WishlistController::viewWishlist

add_to_wishlist:
    path: /add_to_wishlist
    controller: App\Controller\WishlistController::addToWishlist
    methods: [GET,POST]
    options:
        expose: true

delete_wishlist_item:
    path: /delete_wishlist_item/{id}
    controller: App\Controller\WishlistController::deleteWishlistItem
    requirements:
        id: \d+

# Blog
blog_list:
    path: /blog/{page}
    controller: App\Controller\BlogController::listBlog
    defaults: { page: 1 }
    requirements:
        page: \d+

blog_view:
    path: /blog/{slug}
    controller: App\Controller\BlogController::viewBlog


# User Account
user_account:
    path: /user-account
    controller: App\Controller\UserAccountController::userAccount

user_registration:
    path: /user-registration
    controller: App\Controller\UserAccountController::register

get_users:
    path: /get-users
    controller: App\Controller\UserAccountController::getUsers

create_address:
    path: /new-address
    controller: App\Controller\UserAccountController::createAddress

update_address:
    path: /update-address/{id}
    controller: App\Controller\UserAccountController::updateAddress
    requirements:
        page: \d+

# login logout
login:
    path: /login
    controller: App\Controller\AjaxLoginController::login
    methods: [POST]
    options:
        expose: true

logout:
    path: /logout
    controller: App\Controller\UserAccountController::logout

# Admin
#admin:
#    path: /admin
#    controller: App\Controller\AdminDefaultController::login
admin_login:
    path: /administrator
    controller: App\Controller\Admin\SecurityController::login

admin_logout:
    path: /admin/logout

admin:
    path: /admin
    controller: App\Controller\Admin\DefaultController::dashboard

    # Articles
article_list:
    path: /admin/article-list
    controller: App\Controller\Admin\ArticleController::list

article_add:
    path: /admin/article-add
    controller: App\Controller\Admin\ArticleController::create

article_update:
    path: /admin/article-update/{id}
    controller: App\Controller\Admin\ArticleController::update
    requirements:
        id: \d+

article_delete:
    path: /admin/article-delete/{id}
    controller: App\Controller\Admin\ArticleController::delete
    methods: [GET,POST]
    requirements:
        id: \d+
    options:
        expose: true

delete_article_image:
    path: /admin/delete-article-image/{id}
    controller: App\Controller\Admin\ArticleController::deleteArticleImage
    requirements:
        id: \d+

    # Categories
category_list:
    path: /admin/category-list
    controller: App\Controller\Admin\CategoryController::list

category_add:
    path: /admin/category-add
    controller: App\Controller\Admin\CategoryController::create
    methods: [GET,POST]
    options:
        expose: true

category_update:
    path: /admin/category-update/{id}
    controller: App\Controller\Admin\CategoryController::update
    methods: [GET,POST]
    requirements:
        id: \d+
    options:
        expose: true

category_delete:
    path: /admin/category-delete/{id}
    controller: App\Controller\Admin\CategoryController::delete
    methods: [GET,POST]
    requirements:
        id: \d+
    options:
        expose: true

    # Slider
slider_list:
    path: /admin/slider-list
    controller: App\Controller\Admin\SliderController::list

slider_add:
    path: /admin/slider-add
    controller: App\Controller\Admin\SliderController::create
    methods: [GET,POST]
    options:
        expose: true

slider_update:
    path: /admin/slider-update/{id}
    controller: App\Controller\Admin\SliderController::update
    methods: [GET,POST]
    options:
        expose: true
    requirements:
        id: \d+

slider_delete:
    path: /admin/slider-delete/{id}
    controller: App\Controller\Admin\SliderController::delete
    requirements:
        id: \d+

slider_priority:
    path: /admin/slider-priority/{id}/{direction}
    controller: App\Controller\Admin\SliderController::changePriority
    requirements:
        id: \d+

    # Category Slider category_slider_list
category_slider:
    path: /admin/category-slider
    controller: App\Controller\Admin\CategorySliderController::list

category_slider_list:
    path: /admin/category-slider-list/{id}
    controller: App\Controller\Admin\CategorySliderController::sliderList
    requirements:
        id: \d+

category_slider_add:
    path: /admin/category-slider-add
    controller: App\Controller\Admin\CategorySliderController::create
    methods: [GET,POST]
    options:
        expose: true

category_slider_update:
    path: /admin/category-slider-update/{id}
    controller: App\Controller\Admin\CategorySliderController::update
    methods: [GET,POST]
    requirements:
        id: \d+
    options:
        expose: true

category_slider_delete:
    path: /admin/category-slider-delete/{id}
    controller: App\Controller\Admin\CategorySliderController::delete
    requirements:
        id: \d+

category_slider_priority:
    path: /admin/category-slider-priority/{id}/{direction}
    controller: App\Controller\Admin\CategorySliderController::changePriority
    requirements:
        id: \d+

    # Season Promo
seasonpromo_list:
    path: /admin/seasonpromo-list
    controller: App\Controller\Admin\SeasonpromoController::list

seasonpromo_add:
    path: /admin/seasonpromo-add
    controller: App\Controller\Admin\SeasonpromoController::create
    methods: [GET,POST]
    options:
        expose: true

seasonpromo_update:
    path: /admin/seasonpromo-update/{id}
    controller: App\Controller\Admin\SeasonpromoController::update
    requirements:
        id: \d+

seasonpromo_delete:
    path: /admin/seasonpromo-delete/{id}
    controller: App\Controller\Admin\SeasonpromoController::delete
    requirements:
        id: \d+

    # Home Page Modules
home_page_modules:
    path: /admin/home-page-modules
    controller: App\Controller\Admin\HomePageModulesController::list

homepage_modules_priority:
    path: /admin/homepage-modules-priority/{id}/{direction}
    controller: App\Controller\Admin\HomePageModulesController::changePriority
    requirements:
        id: \d+