index:
    path: /
    controller: App\Controller\DefaultController::index
    methods: [GET]
    options:
        expose: true

404:
    path: /404-not-found
    controller: App\Controller\DefaultController::notFound

# Home page search
search_for_anosia:
    path: /search/anosia
    controller: App\Controller\AjaxSearchController::searchForAnosia
    methods: [GET]
    options:
        expose: true
search:
    path: /search/website
    controller: App\Controller\AjaxSearchController::search
    methods: [GET,POST]
    options:
        expose: true

# Products
products_list:
    path: /products/{slug}/{page}
    controller: App\Controller\ProductController::listProducts
    defaults:
        page: 1
    requirements:
        page: \d+
    methods: [GET,POST]
    options:
        expose: true
brand_products_list:
    path: /brand/{slug}/{page}
    controller: App\Controller\ProductController::listBrandProducts
    defaults: { page: 1 }
#    methods: [POST]
#    options:
#        expose: true
    requirements:
        page: \d+
brands_list:
    path: /brands/{page}
    controller: App\Controller\ProductController::listBrands
    defaults: { page: 1 }
    requirements:
        page: \d+
product_view:
    path: /product/{id}
    controller: App\Controller\ProductController::viewProduct
    requirements:
        id: \d+
    methods: [GET]
    options:
        expose: true
product_search:
    path: /product/search/{page}
    controller: App\Controller\ProductController::searchResults
    defaults: { page: 1 }
    requirements:
        page: \d+
    methods: [GET]
    options:
        expose: true
product_search_anosia:
    path: /product/search/anosia/{page}
    controller: App\Controller\ProductController::searchAnosiaResults
    defaults: { page: 1 }
    requirements:
        page: \d+
home_best_seller:
    path: /best-seller
    controller: App\Controller\AjaxHomePageController::bestSellers
    methods: [POST]
    options:
        expose: true

# Orders / Cart
cart_view:
    path: /cart
    controller: App\Controller\CartController::viewCart
    methods: [GET,POST]
    options:
        expose: true
update_cart:
    path: /update-cart
    controller: App\Controller\CartController::updateCart
    methods: [POST]
add_to_cart:
    path: /add_to_cart
    controller: App\Controller\AjaxCartController::addToCart
    methods: [POST]
    options:
        expose: true
load_top_cart:
    path: /top-cart
    controller: App\Controller\AjaxCartController::loadTopCart
    methods: [GET,POST]
    options:
        expose: true
delete_top_cart_item:
    path: /delete-top-cart-item/
    controller: App\Controller\AjaxCartController::deleteTopCartItem
    methods: [GET,POST]
    options:
        expose: true
delete_cart_item:
    path: /delete-cart-item/{id}
    controller: App\Controller\CartController::deleteCartItem
    requirements:
        id: \d+
check_coupon:
    path: /cart/check-coupon
    controller: App\Controller\AjaxCartController::checkCoupon
    methods: [GET,POST]
    options:
        expose: true
remove_coupon:
    path: /cart/remove-coupon
    controller: App\Controller\AjaxCartController::removeCoupon
    methods: [GET,POST]
    options:
        expose: true

# Orders Checkout
checkout:
    path: /order/checkout
    controller: App\Controller\CheckoutController::checkout
#    defaults: { step: 1 }
#    requirements:
#        id: \d+
    methods: [GET,POST]
    options:
        expose: true
complete_checkout:
    path: /order/complete-checkout
    controller: App\Controller\CheckoutController::completeCheckout
    methods: [GET,POST]
    options:
        expose: true
step1_submit:
    path: /order/checkout-step1
    controller: App\Controller\AjaxCheckoutController::step1Submit
    methods: [GET,POST]
    options:
        expose: true
check_if_user_exists:
    path: /order/check-if-user-exists
    controller: App\Controller\AjaxCheckoutController::checkIfUserExists
    methods: [GET,POST]
    options:
        expose: true
get_pireaus_ticket:
    path: /order/get-pireaus-ticket
    controller: App\Controller\CheckoutController::getPireausTicket
    methods: [POST]
    options:
        expose: true


#guest_checkout: #Todo: to be deleted possible with get address
#    path: /checkout/guest/{step}
#    controller: App\Controller\CheckoutController::guestCheckout
#    defaults: { step: 1 }
#    requirements:
#        id: \d+
get_address:
    path: /get-address
    controller: App\Controller\AjaxCheckoutController::getAddress
    methods: [GET,POST]
    options:
        expose: true
paypal_result:
    path: /paypal/result
    controller: App\Controller\PaypalController::return
paypal_cancel:
    path: /paypal/cancel
    controller: App\Controller\PaypalController::cancel
pireus_post:
    path: /pireaus/post
    controller: App\Controller\PireausController::pireausPost
pireaus_success:
    path: /checkout/success
    controller: App\Controller\PireausController::success
pireaus_cancel:
    path: /checkout/cancel
    controller: App\Controller\PireausController::cancel
pireaus_failure:
    path: /checkout/failure
    controller: App\Controller\PireausController::failure
pireaus_iframe:
    path: /checkout/online-payment
    controller: App\Controller\PireausController::pireausIframe

# Wishlist
wishlist_view:
    path: /wishlist
    controller: App\Controller\WishlistController::viewWishlist
add_to_wishlist:
    path: /add_to_wishlist
    controller: App\Controller\WishlistController::addToWishlist
    methods: [GET,POST]
    options:
        expose: true
delete_wishlist_item:
    path: /delete_wishlist_item/{id}
    controller: App\Controller\WishlistController::deleteWishlistItem
    requirements:
        id: \d+

# Blog
blog_list:
    path: /blog/{page}
    controller: App\Controller\BlogController::listBlog
    defaults: { page: 1 }
    requirements:
        page: \d+
blog_view:
    path: /blog/{slug}
    controller: App\Controller\BlogController::viewBlog


# User Account
user_account:
    path: /user-account
    controller: App\Controller\UserAccountController::userAccount
user_registration:
    path: /user-registration
    controller: App\Controller\UserAccountController::register
get_users:
    path: /get-users
    controller: App\Controller\UserAccountController::getUsers
create_address:
    path: /new-address
    controller: App\Controller\UserAccountController::createAddress
update_address:
    path: /update-address/{id}
    controller: App\Controller\UserAccountController::updateAddress
    requirements:
        id: \d+
delete_address:
    path: /delete-address
    controller: App\Controller\UserAccountController::deleteAddress
    methods: [GET,POST]
    options:
        expose: true
newsletter_registration:
    path: /newsletter/registration
    controller: App\Controller\AjaxNewsletterController::newsletterRegistration
    options:
        expose: true
user-order:
    path: /user/order/{id}
    controller: App\Controller\UserAccountController::viewOrder
    requirements:
        id: \d+
user_forgot_password:
    path: /user/forgot-password
    controller: App\Controller\UserAccountController::forgotPassword
user_send_password_email:
    path: /user/password-email
    controller: App\Controller\UserAccountController::sendPasswordEmail
user_reset_password:
    path: /user/reset-password
    controller: App\Controller\UserAccountController::resetPassword

# Courier voucher tracker
courier_tracker:
    path: /courier/tracker/{voucher}
    controller: App\Controller\CourierTrackerController::trackVoucher
    options:
        expose: true
# login logout
login:
    path: /login
    controller: App\Controller\AjaxLoginController::login
    methods: [POST]
    options:
        expose: true
logout:
    path: /logout
    controller: App\Controller\UserAccountController::logout

# Skroutz XML
skroutz_xml:
    path: /skroutz/xml
    controller: App\Controller\SkroutzController::createXML

# Admin
admin_login:
    path: /administrator
    controller: App\Controller\Admin\SecurityController::login
admin_logout:
    path: /admin/logout
admin:
    path: /admin
    controller: App\Controller\Admin\DefaultController::dashboard

    # Articles
article_list:
    path: /admin/article-list
    controller: App\Controller\Admin\ArticleController::list
article_add:
    path: /admin/article-add
    controller: App\Controller\Admin\ArticleController::create
article_update:
    path: /admin/article-update/{id}
    controller: App\Controller\Admin\ArticleController::update
    requirements:
        id: \d+
article_delete:
    path: /admin/article-delete/{id}
    controller: App\Controller\Admin\ArticleController::delete
    methods: [GET,POST]
    requirements:
        id: \d+
    options:
        expose: true
delete_article_image:
    path: /admin/delete-article-image/{id}
    controller: App\Controller\Admin\ArticleController::deleteArticleImage
    requirements:
        id: \d+

    # Categories
category_list:
    path: /admin/category-list
    controller: App\Controller\Admin\CategoryController::list
category_add:
    path: /admin/category-add
    controller: App\Controller\Admin\CategoryController::create
    methods: [GET,POST]
    options:
        expose: true
category_update:
    path: /admin/category-update/{id}
    controller: App\Controller\Admin\CategoryController::update
    methods: [GET,POST]
    requirements:
        id: \d+
    options:
        expose: true
category_delete:
    path: /admin/category-delete/{id}
    controller: App\Controller\Admin\CategoryController::delete
    methods: [GET,POST]
    requirements:
        id: \d+
    options:
        expose: true

    # Slider
slider_list:
    path: /admin/slider-list
    controller: App\Controller\Admin\SliderController::list
slider_add:
    path: /admin/slider-add
    controller: App\Controller\Admin\SliderController::create
    methods: [GET,POST]
    options:
        expose: true
slider_update:
    path: /admin/slider-update/{id}
    controller: App\Controller\Admin\SliderController::update
    methods: [GET,POST]
    options:
        expose: true
    requirements:
        id: \d+
slider_delete:
    path: /admin/slider-delete/{id}
    controller: App\Controller\Admin\SliderController::delete
    methods: [GET,POST]
    requirements:
        id: \d+
    options:
        expose: true
slider_priority:
    path: /admin/slider-priority/{id}/{direction}
    controller: App\Controller\Admin\SliderController::changePriority
    requirements:
        id: \d+

    # Category Slider category_slider_list
category_slider:
    path: /admin/category-slider
    controller: App\Controller\Admin\CategorySliderController::list
category_slider_list:
    path: /admin/category-slider-list/{id}
    controller: App\Controller\Admin\CategorySliderController::sliderList
    requirements:
        id: \d+
category_slider_add:
    path: /admin/category-slider-add
    controller: App\Controller\Admin\CategorySliderController::create
    methods: [GET,POST]
    options:
        expose: true
category_slider_update:
    path: /admin/category-slider-update/{id}
    controller: App\Controller\Admin\CategorySliderController::update
    methods: [GET,POST]
    requirements:
        id: \d+
    options:
        expose: true
category_slider_delete:
    path: /admin/category-slider-delete/{id}
    controller: App\Controller\Admin\CategorySliderController::delete
    requirements:
        id: \d+
    options:
        expose: true
category_slider_priority:
    path: /admin/category-slider-priority/{id}/{direction}
    controller: App\Controller\Admin\CategorySliderController::changePriority
    requirements:
        id: \d+

    # Season Promo
seasonpromo_list:
    path: /admin/seasonpromo-list
    controller: App\Controller\Admin\SeasonpromoController::list
seasonpromo_add:
    path: /admin/seasonpromo-add
    controller: App\Controller\Admin\SeasonpromoController::create
    methods: [GET,POST]
    options:
        expose: true
seasonpromo_update:
    path: /admin/seasonpromo-update/{id}
    controller: App\Controller\Admin\SeasonpromoController::update
    requirements:
        id: \d+
seasonpromo_delete:
    path: /admin/seasonpromo-delete/{id}
    controller: App\Controller\Admin\SeasonpromoController::delete
    requirements:
        id: \d+

    # Home Page Modules
home_page_modules:
    path: /admin/home-page-modules
    controller: App\Controller\Admin\HomePageModulesController::list
#home_page_module:
#    path: /admin/home-page-module/{slug}
#    controller: App\Controller\Admin\HomePageModulesController::update
our_corner:
    path: /admin/home-page-module/our-corner
    controller: App\Controller\Admin\HomePageModulesController::ourCorner
our_corner_update:
    path: /admin/home-page-module/our-corner-update/{id}
    controller: App\Controller\Admin\HomePageModulesController::ourCornerUpdate
    requirements:
        id: \d+
    methods: [GET,POST]
    options:
        expose: true
latest_offers:
    path: /admin/home-page-module/latest-offers
    controller: App\Controller\Admin\HomePageModulesController::latestOffers
latest_offer_add:
    path: /admin/home-page-module/latest-offers-add
    controller: App\Controller\Admin\HomePageModulesController::latestOfferAdd
    methods: [GET,POST]
    options:
        expose: true
latest_offer_update:
    path: /admin/home-page-module/latest-offers-update
    controller: App\Controller\Admin\HomePageModulesController::latestOfferUpdate
    methods: [GET,POST]
    options:
        expose: true
promo_categories:
    path: /admin/home-page-modules/promo-categories
    controller: App\Controller\Admin\HomePageModulesController::promoCategoriesList
promo_categories_add:
    path: /admin/home-page-modules/promo-category-add
    controller: App\Controller\Admin\HomePageModulesController::promoCategoriesCreate
    methods: [GET,POST]
    options:
        expose: true
promo_categories_update:
    path: /admin/home-page-modules/promo-category-update/{id}
    controller: App\Controller\Admin\HomePageModulesController::promoCategoriesUpdate
    methods: [GET,POST]
    options:
        expose: true
    requirements:
        id: \d+
promo_categories_delete:
    path: /admin/home-page-modules/promo-category-delete/{id}
    controller: App\Controller\Admin\HomePageModulesController::promoCategoriesDelete
    methods: [GET,POST]
    requirements:
        id: \d+
    options:
        expose: true
promo_categories_priority:
    path: /admin/home-page-modules/promo-category/{id}/{direction}
    controller: App\Controller\Admin\HomePageModulesController::promoCategoriesChangePriority
    requirements:
        id: \d+


#fb callback login
fb_callback:
    path: /fb-callback
    controller: App\Controller\AjaxLoginController::fbCallback
    methods: [GET]
    options:
        expose: true

homepage_modules_priority:
    path: /admin/homepage-modules-priority/{id}/{direction}
    controller: App\Controller\Admin\HomePageModulesController::changePriority
    requirements:
        id: \d+

# Csv Import & MIGRATIONS
csv_import:
    path: /csv/import
    controller: App\Controller\CsvImport::importData
csv_import_products:
    path: /csv/import-products
    controller: App\Controller\CsvImport::importProducts
csv_import_seo:
    path: /csv/import-seo
    controller: App\Controller\CsvImport::importSeo
csv_import_old_slugs:
    path: /csv/import-old-slugs
    controller: App\Controller\CsvImport::importOldSlugs
csv_import_alternative_categories:
    path: /csv/import-alternative-categories
    controller: App\Controller\CsvImport::importAlternativeCategories
csv_import_product_categories:
    path: /csv/import-product-categories
    controller: App\Controller\CsvImport::importProductCategories

get_images:
    path: /migrate/images
    controller: App\Controller\MigrateController::migrateImages
update_s1:
    path: /update-s1
    controller: App\Controller\MigrateController::updateS1
updateFromTempImages:
    path: /migrate/temp-images
    controller: App\Controller\MigrateController::updateFromTempImages
getProductsWithNoImage:
    path: /migrate/products-no-images
    controller: App\Controller\MigrateController::getProductsWithNoImage
updateMigratedProductsWithS1Id:
    path: /migrate/s1id
    controller: App\Controller\MigrateController::updateMigratedProductsWithS1Id
getProductsWithNoImageFromS1:
    path: /migrate/images-from-s1
    controller: App\Controller\MigrateController::getProductsWithNoImageFromS1
updateAnosiaKeywordsSlug:
    path: /update/anosia-keywords/slug
    controller: App\Controller\MigrateController::updateAnosiaKeywordsSlug
updateProductsFromS1:
    path: /migrate/update-products-from-s1
    controller: App\Controller\MigrateController::updateProductsFromS1

# Cron Jobs
create_categories:
    path: /synchronize/categories
    controller: App\Controller\CronJobsController::synchronizeCategories
syncronize_products:
    path: /synchronize/products
    controller: App\Controller\CronJobsController::synchronizeProducts
synchronize_availability_types:
    path: /synchronize/availability-types
    controller: App\Controller\CronJobsController::synchronizeAvailabilityTypes
synchronize_parameters:
    path: /synchronize/parameters
    controller: App\Controller\CronJobsController::synchronizeParameters
synchronize_countries:
    path: /synchronize/countries
    controller: App\Controller\CronJobsController::synchronizeCountries
test:
    path: /test
    controller: App\Controller\TestController::testEmail