index:
    path: /
    controller: App\Controller\DefaultController::index

# Products
products_list:
    path: /products/{id}/{page}
    controller: App\Controller\ProductController::listProducts
    defaults: { page: 1 }
    requirements:
        id: \d+
        page: \d+

product_view:
    path: /product/{id}
    controller: App\Controller\ProductController::viewProduct
    requirements:
        id: \d+

product_quick_view:
    path: /product/quick/{id}
    controller: App\Controller\ProductController::quickviewProduct
    requirements:
        id: \d+

product_search:
    path: /product/search
    controller: App\Controller\ProductController::searchResults
    methods: [POST]

# Orders / Cart
cart_view:
    path: /cart
    controller: App\Controller\CartController::viewCart

add_to_cart:
    path: /add_to_cart
    controller: App\Controller\AjaxCartController::addToCart
    methods: [POST]
    options:
        expose: true

load_top_cart:
    path: /top-cart
    controller: App\Controller\AjaxCartController::loadTopCart
    methods: [GET,POST]
    options:
        expose: true

delete_top_cart_item:
    path: /delete-top-cart-item/
    controller: App\Controller\AjaxCartController::deleteTopCartItem
    methods: [GET,POST]
    options:
        expose: true

delete_cart_item:
    path: /delete-cart-item/{id}
    controller: App\Controller\CartController::deleteCartItem
    requirements:
        id: \d+

# Orders Checkout
checkout:
    path: /checkout
    controller: App\Controller\CheckoutController::checkout

# Wishlist
add_to_wishlist:
    path: /wishlist/{id}
    controller: App\Controller\WishlistController::addToWishlist
    methods: [GET,POST]
    options:
        expose: true
    requirements:
        id: \d+

# Blog
blog_list:
    path: /blog/{page}
    controller: App\Controller\BlogController::listBlog
    defaults: { page: 1 }
    requirements:
        page: \d+

# User Account
user_account:
    path: /user-account
    controller: App\Controller\UserAccountController::userAccount

user_registration:
    path: /user-registration
    controller: App\Controller\UserAccountController::register

get_users:
    path: /get-users
    controller: App\Controller\UserAccountController::getUsers

login:
    path: /login
    controller: App\Controller\AjaxLoginController::login
    methods: [POST]
    options:
        expose: true